### ISSUE TITLE
CT Build failed with status code 1

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/center-and-spread#27]
```
center-and-spread : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
>> TypeScript compilation complete: 5206ms
11:11:57 AM, 371 ms: ../center-and-spread/js/center-and-spread-main.ts
11:11:57 AM, 16 ms: ../center-and-spread/js/center-and-spread-phet-io-overrides.js
11:11:57 AM, 25 ms: ../center-and-spread/js/centerAndSpread.ts
11:11:57 AM, 32 ms: ../center-and-spread/js/centerAndSpreadStrings.ts
11:11:57 AM, 27 ms: ../center-and-spread/js/common/CASColors.ts
11:11:57 AM, 18 ms: ../center-and-spread/js/common/CASConstants.ts
11:11:57 AM, 16 ms: ../center-and-spread/js/common/CASQueryParameters.ts
11:11:57 AM, 31 ms: ../center-and-spread/js/common/CASScreen.ts
11:11:57 AM, 64 ms: ../center-and-spread/js/common/model/CASModel.ts
11:11:57 AM, 60 ms: ../center-and-spread/js/common/model/CASObject.ts
11:11:57 AM, 21 ms: ../center-and-spread/js/common/model/CASObjectType.ts
11:11:57 AM, 22 ms: ../center-and-spread/js/common/model/CardModel.ts
11:11:57 AM, 39 ms: ../center-and-spread/js/common/model/SoccerModel.ts
11:11:57 AM, 33 ms: ../center-and-spread/js/common/view/BackgroundNode.ts
11:11:57 AM, 28 ms: ../center-and-spread/js/common/view/CASAccordionBox.ts
11:11:57 AM, 39 ms: ../center-and-spread/js/common/view/CASObjectNode.ts
11:11:57 AM, 31 ms: ../center-and-spread/js/common/view/CASScreenView.ts
11:11:57 AM, 33 ms: ../center-and-spread/js/common/view/CardNode.ts
11:11:57 AM, 27 ms: ../center-and-spread/js/common/view/KickButtonGroup.ts
11:11:57 AM, 87 ms: ../center-and-spread/js/common/view/NumberCardContainer.ts
11:11:58 AM, 24 ms: ../center-and-spread/js/common/view/QuestionBar.ts
11:11:58 AM, 28 ms: ../center-and-spread/js/common/view/SoccerScreenView.ts
11:11:58 AM, 21 ms: ../center-and-spread/js/common/view/TopRepresentationCheckboxGroup.ts
11:11:58 AM, 17 ms: ../center-and-spread/js/lab/LabScreen.ts
11:11:58 AM, 22 ms: ../center-and-spread/js/lab/model/LabModel.ts
11:11:58 AM, 18 ms: ../center-and-spread/js/lab/view/LabScreenView.ts
11:11:58 AM, 18 ms: ../center-and-spread/js/mean-and-median/MeanAndMedianScreen.ts
11:11:58 AM, 16 ms: ../center-and-spread/js/mean-and-median/model/MeanAndMedianModel.ts
11:11:58 AM, 16 ms: ../center-and-spread/js/mean-and-median/view/MeanAndMedianScreenView.ts
11:11:58 AM, 20 ms: ../center-and-spread/js/median/MedianScreen.ts
11:11:58 AM, 15 ms: ../center-and-spread/js/median/model/MedianModel.ts
11:11:58 AM, 21 ms: ../center-and-spread/js/median/view/MedianScreenView.ts
11:11:58 AM, 17 ms: ../center-and-spread/js/spread/SpreadScreen.ts
11:11:58 AM, 23 ms: ../center-and-spread/js/spread/model/SpreadModel.ts
11:11:58 AM, 24 ms: ../center-and-spread/js/spread/view/SpreadScreenView.ts
11:11:58 AM, 38 ms: ../center-and-spread/images/ball_png.js
Building runnable repository (center-and-spread, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 6030ms
>> Production minification complete: 30818ms (1665099 bytes)
>> Debug minification complete: 1ms (18301646 bytes)
Building brand: phet-io
>> Webpack build complete: 4259ms
>> Production minification complete: 29575ms (1697556 bytes)
>> Debug minification complete: 27507ms (2001578 bytes)
>> No client guides found at ../phet-io-client-guides/center-and-spread/, no guides being built.
>> TypeScript compilation complete: 920ms
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: Full API expected but not created from puppeteer step, likely caused by https://github.com/phetsims/chipper/issues/1022.
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1644599699878/chipper/js/grunt/copySupplementalPhetioFiles.js:323:5)
at async module.exports (/data/share/phet/continuous-testing/ct-snapshots/1644599699878/chipper/js/grunt/buildRunnable.js:355:5)
at async /data/share/phet/continuous-testing/ct-snapshots/1644599699878/chipper/js/grunt/Gruntfile.js:283:11
at async wrap (/data/share/phet/continuous-testing/ct-snapshots/1644599699878/chipper/js/grunt/Gruntfile.js:56:7)
Full Error details:
AssertionError [ERR_ASSERTION]: Full API expected but not created from puppeteer step, likely caused by https://github.com/phetsims/chipper/issues/1022.

Error in fulfilling chunk Promise: [Error: TypeError: Cannot read properties of undefined (reading 'valueProperty')
at new gg (http://localhost:40177/center-and-spread/build/phet-io/center-and-spread_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:887:1376899)
at ap.createElement (http://localhost:40177/center-and-spread/build/phet-io/center-and-spread_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:887:1378710)
at ap.createArchetype (http://localhost:40177/center-and-spread/build/phet-io/center-and-spread_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:887:956106)
at new c (http://localhost:40177/center-and-spread/build/phet-io/center-and-spread_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:887:954693)
at new ap (http://localhost:40177/center-and-spread/build/phet-io/center-and-spread_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:887:1303801)
at new Pg (http://localhost:40177/center-and-spread/build/phet-io/center-and-spread_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:887:1378696)
at new Eg (http://localhost:40177/center-and-spread/build/phet-io/center-and-spread_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:887:1382457)
at Cg.createView (http://localhost:40177/center-and-spread/build/phet-io/center-and-spread_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:887:1383195)
at Cg.initializeView (http://localhost:40177/center-and-spread/build/phet-io/center-and-spread_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:887:1049519)
at Array.<anonymous> (http://localhost:40177/center-and-spread/build/phet-io/center-and-spread_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:887:1299904)]
Snapshot from 2/11/2022, 10:14:59 AM

----------------------------------

center-and-spread : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644599699878/studio/?sim=center-and-spread&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-spread%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1644599699878%22%2C%22timestamp%22%3A1644605109285%7D
Uncaught Error: Uncaught TypeError: Cannot read properties of undefined (reading 'valueProperty')
TypeError: Cannot read properties of undefined (reading 'valueProperty')
at new CardNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644599699878/chipper/dist/js/center-and-spread/js/common/view/CardNode.js:32:15)
at PhetioGroup.createElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644599699878/chipper/dist/js/center-and-spread/js/common/view/NumberCardContainer.js:52:14)
at PhetioGroup.createArchetype (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644599699878/chipper/dist/js/tandem/js/PhetioDynamicElementContainer.js:184:30)
at new PhetioDynamicElementContainer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644599699878/chipper/dist/js/tandem/js/PhetioDynamicElementContainer.js:84:27)
at new PhetioGroup (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644599699878/chipper/dist/js/tandem/js/PhetioGroup.js:46:5)
at new NumberCardContainer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644599699878/chipper/dist/js/center-and-spread/js/common/view/NumberCardContainer.js:51:28)
at new MedianScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644599699878/chipper/dist/js/center-and-spread/js/median/view/MedianScreenView.js:30:32)
at MedianScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644599699878/chipper/dist/js/center-and-spread/js/median/MedianScreen.js:28:18)
at MedianScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644599699878/chipper/dist/js/joist/js/Screen.js:219:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644599699878/chipper/dist/js/joist/js/Sim.js:680:16)
id: Bayes Chrome
Snapshot from 2/11/2022, 10:14:59 AM
```

**Comment by samreid** [comment]
CT seems clear and I tested a local phet-io build.  It seems ok now, thanks for reporting it!  Let's reopen or create a new issue if it happens again.
