### ISSUE TITLE
CT all descendants must be disposed by the next frame

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/center-and-spread#36]
```
center-and-spread : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645092337740/center-and-spread/center-and-spread_en.html?continuousTest=%7B%22test%22%3A%5B%22center-and-spread%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1645092337740%22%2C%22timestamp%22%3A1645096175643%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: centerAndSpread.meanAndMedianScreen.model.soccerBallGroup.soccerBall_0.isMedianObjectProperty
Error: Assertion failed: All descendants must be disposed by the next frame: centerAndSpread.meanAndMedianScreen.model.soccerBallGroup.soccerBall_0.isMedianObjectProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645092337740/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645092337740/chipper/dist/js/tandem/js/PhetioObject.js:528:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645092337740/chipper/dist/js/tandem/js/PhetioObject.js:527:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645092337740/chipper/dist/js/axon/js/Timer.js:30:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645092337740/chipper/dist/js/axon/js/TinyEmitter.js:82:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645092337740/chipper/dist/js/joist/js/Sim.js:796:25)
id: Bayes Chrome
Snapshot from 2/17/2022, 3:05:37 AM

----------------------------------

center-and-spread : phet-io-input-record-and-playback-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645092337740/phet-io-wrappers/input-record-and-playback/?sim=center-and-spread&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-spread%22%2C%22phet-io-input-record-and-playback-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1645092337740%22%2C%22timestamp%22%3A1645095883541%7D
Uncaught Error: Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: centerAndSpread.medianScreen.model.soccerBallGroup.soccerBall_0.isMedianObjectProperty
Error: Assertion failed: All descendants must be disposed by the next frame: centerAndSpread.medianScreen.model.soccerBallGroup.soccerBall_0.isMedianObjectProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645092337740/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645092337740/chipper/dist/js/tandem/js/PhetioObject.js:528:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645092337740/chipper/dist/js/tandem/js/PhetioObject.js:527:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645092337740/chipper/dist/js/axon/js/Timer.js:30:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645092337740/chipper/dist/js/axon/js/TinyEmitter.js:82:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645092337740/chipper/dist/js/joist/js/Sim.js:796:25)
id: Bayes Chrome
Snapshot from 2/17/2022, 3:05:37 AM

----------------------------------

center-and-spread : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645092337740/studio/?sim=center-and-spread&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-spread%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1645092337740%22%2C%22timestamp%22%3A1645095563223%7D
Uncaught Error: Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: centerAndSpread.medianScreen.model.soccerBallGroup.soccerBall_0.isMedianObjectProperty
Error: Assertion failed: All descendants must be disposed by the next frame: centerAndSpread.medianScreen.model.soccerBallGroup.soccerBall_0.isMedianObjectProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645092337740/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645092337740/chipper/dist/js/tandem/js/PhetioObject.js:528:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645092337740/chipper/dist/js/tandem/js/PhetioObject.js:527:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645092337740/chipper/dist/js/axon/js/Timer.js:30:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645092337740/chipper/dist/js/axon/js/TinyEmitter.js:82:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645092337740/chipper/dist/js/joist/js/Sim.js:796:25)
id: Bayes Chrome
Snapshot from 2/17/2022, 3:05:37 AM
```

**Comment by samreid** [comment]
Fixed as part of https://github.com/phetsims/center-and-spread/issues/32, closing.
