### ISSUE TITLE
CT: mutliple failures

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-spread#70]
```
center-and-spread : fuzz : built-phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/center-and-spread/build/phet-io/center-and-spread_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22center-and-spread%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1646306694541%22%2C%22timestamp%22%3A1646311635483%7D&fuzz&memoryLimit=1000&phetioStandalone
Query: fuzz&memoryLimit=1000&phetioStandalone
Uncaught TypeError: Cannot read properties of undefined (reading 'typeName')
TypeError: Cannot read properties of undefined (reading 'typeName')
at o (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/center-and-spread/build/phet-io/center-and-spread_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22center-and-spread%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1646306694541%22%2C%22timestamp%22%3A1646311635483%7D&fuzz&memoryLimit=1000&phetioStandalone:887:980818)
at Object.getData (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/center-and-spread/build/phet-io/center-and-spread_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22center-and-spread%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1646306694541%22%2C%22timestamp%22%3A1646311635483%7D&fuzz&memoryLimit=1000&phetioStandalone:887:15054)
at q.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/center-and-spread/build/phet-io/center-and-spread_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22center-and-spread%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1646306694541%22%2C%22timestamp%22%3A1646311635483%7D&fuzz&memoryLimit=1000&phetioStandalone:887:963336)
at q._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/center-and-spread/build/phet-io/center-and-spread_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22center-and-spread%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1646306694541%22%2C%22timestamp%22%3A1646311635483%7D&fuzz&memoryLimit=1000&phetioStandalone:887:14939)
at q.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/center-and-spread/build/phet-io/center-and-spread_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22center-and-spread%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1646306694541%22%2C%22timestamp%22%3A1646311635483%7D&fuzz&memoryLimit=1000&phetioStandalone:887:14564)
at q.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/center-and-spread/build/phet-io/center-and-spread_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22center-and-spread%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1646306694541%22%2C%22timestamp%22%3A1646311635483%7D&fuzz&memoryLimit=1000&phetioStandalone:887:15596)
at Mc.kickBall (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/center-and-spread/build/phet-io/center-and-spread_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22center-and-spread%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1646306694541%22%2C%22timestamp%22%3A1646311635483%7D&fuzz&memoryLimit=1000&phetioStandalone:887:1331894)
at Mc.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/center-and-spread/build/phet-io/center-and-spread_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22center-and-spread%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1646306694541%22%2C%22timestamp%22%3A1646311635483%7D&fuzz&memoryLimit=1000&phetioStandalone:887:1332753)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/center-and-spread/build/phet-io/center-and-spread_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22center-and-spread%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1646306694541%22%2C%22timestamp%22%3A1646311635483%7D&fuzz&memoryLimit=1000&phetioStandalone:887:1298628
at p.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/center-and-spread/build/phet-io/center-and-spread_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22center-and-spread%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1646306694541%22%2C%22timestamp%22%3A1646311635483%7D&fuzz&memoryLimit=1000&phetioStandalone:887:2038)
id: Bayes Chrome
Snapshot from 3/3/2022, 4:24:54 AM

----------------------------------

center-and-spread : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/center-and-spread/center-and-spread_en.html?continuousTest=%7B%22test%22%3A%5B%22center-and-spread%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1646306694541%22%2C%22timestamp%22%3A1646309863166%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: fell back to root serialization state for centerAndSpread.medianScreen.model.soccerBallGroup.soccerBall_0.animationModeProperty. Potential solutions:
* mark the type as phetioState: false
* create a custom toStateObject method in your IO Type
* perhaps you have everything right, but forgot to pass in the IOType via phetioType in the constructor
Error: Assertion failed: fell back to root serialization state for centerAndSpread.medianScreen.model.soccerBallGroup.soccerBall_0.animationModeProperty. Potential solutions:
* mark the type as phetioState: false
* create a custom toStateObject method in your IO Type
* perhaps you have everything right, but forgot to pass in the IOType via phetioType in the constructor
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/assert/js/assert.js:25:13)
at Object.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/tandem/js/types/IOType.js:444:15)
at IOType.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/tandem/js/types/IOType.js:182:32)
at PhetioStateEngine.getValueJSON (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/phet-io/js/PhetioStateEngine.js:107:49)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/phet-io/js/PhetioStateEngine.js:165:32
at Array.forEach (<anonymous>)
at PhetioStateEngine.getState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/phet-io/js/PhetioStateEngine.js:161:38)
at PhetioStateEngine.initialize (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/phet-io/js/PhetioStateEngine.js:439:30)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/phet-io/js/phetioEngine.js:241:32
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
id: Bayes Chrome
Snapshot from 3/3/2022, 4:24:54 AM

----------------------------------

center-and-spread : phet-io-input-record-and-playback-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/phet-io-wrappers/input-record-and-playback/?sim=center-and-spread&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-spread%22%2C%22phet-io-input-record-and-playback-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1646306694541%22%2C%22timestamp%22%3A1646310239488%7D
Uncaught Error: Uncaught Error: Assertion failed: fell back to root serialization state for centerAndSpread.medianScreen.model.soccerBallGroup.soccerBall_0.animationModeProperty. Potential solutions:
* mark the type as phetioState: false
* create a custom toStateObject method in your IO Type
* perhaps you have everything right, but forgot to pass in the IOType via phetioType in the constructor
Error: Assertion failed: fell back to root serialization state for centerAndSpread.medianScreen.model.soccerBallGroup.soccerBall_0.animationModeProperty. Potential solutions:
* mark the type as phetioState: false
* create a custom toStateObject method in your IO Type
* perhaps you have everything right, but forgot to pass in the IOType via phetioType in the constructor
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/assert/js/assert.js:25:13)
at Object.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/tandem/js/types/IOType.js:444:15)
at IOType.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/tandem/js/types/IOType.js:182:32)
at PhetioStateEngine.getValueJSON (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/phet-io/js/PhetioStateEngine.js:107:49)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/phet-io/js/PhetioStateEngine.js:165:32
at Array.forEach (<anonymous>)
at PhetioStateEngine.getState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/phet-io/js/PhetioStateEngine.js:161:38)
at PhetioStateEngine.initialize (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/phet-io/js/PhetioStateEngine.js:439:30)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/phet-io/js/phetioEngine.js:241:32
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
id: Bayes Chrome
Snapshot from 3/3/2022, 4:24:54 AM

----------------------------------

center-and-spread : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/phet-io-wrappers/state/?sim=center-and-spread&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-spread%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1646306694541%22%2C%22timestamp%22%3A1646309988991%7D
Uncaught Error: Uncaught Error: Assertion failed: fell back to root serialization state for centerAndSpread.medianScreen.model.soccerBallGroup.soccerBall_0.animationModeProperty. Potential solutions:
* mark the type as phetioState: false
* create a custom toStateObject method in your IO Type
* perhaps you have everything right, but forgot to pass in the IOType via phetioType in the constructor
Error: Assertion failed: fell back to root serialization state for centerAndSpread.medianScreen.model.soccerBallGroup.soccerBall_0.animationModeProperty. Potential solutions:
* mark the type as phetioState: false
* create a custom toStateObject method in your IO Type
* perhaps you have everything right, but forgot to pass in the IOType via phetioType in the constructor
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/assert/js/assert.js:25:13)
at Object.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/tandem/js/types/IOType.js:444:15)
at IOType.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/tandem/js/types/IOType.js:182:32)
at PhetioStateEngine.getValueJSON (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/phet-io/js/PhetioStateEngine.js:107:49)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/phet-io/js/PhetioStateEngine.js:165:32
at Array.forEach (<anonymous>)
at PhetioStateEngine.getState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/phet-io/js/PhetioStateEngine.js:161:38)
at PhetioStateEngine.initialize (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/phet-io/js/PhetioStateEngine.js:439:30)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/phet-io/js/phetioEngine.js:241:32
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
id: Bayes Chrome
Snapshot from 3/3/2022, 4:24:54 AM

----------------------------------

center-and-spread : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/phet-io-wrappers/phet-io-wrappers-tests.html?sim=center-and-spread
3 out of 4 tests passed. 1 failed.
SimTests: center-and-spread: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: fell back to root serialization state for centerAndSpread.medianScreen.model.soccerBallGroup.soccerBall_0.animationModeProperty. Potential solutions:
* mark the type as phetioState: false
* create a custom toStateObject method in your IO Type
* perhaps you have everything right, but forgot to pass in the IOType via phetioType in the constructor
Error: Assertion failed: fell back to root serialization state for centerAndSpread.medianScreen.model.soccerBallGroup.soccerBall_0.animationModeProperty. Potential solutions:
* mark the type as phetioState: false
* create a custom toStateObject method in your IO Type
* perhaps you have everything right, but forgot to pass in the IOType via phetioType in the constructor
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/assert/js/assert.js:25:13)
at Object.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/tandem/js/types/IOType.js:444:15)
at IOType.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/tandem/js/types/IOType.js:182:32)
at PhetioStateEngine.getValueJSON (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/phet-io/js/PhetioStateEngine.js:107:49)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/phet-io/js/PhetioStateEngine.js:165:32
at Array.forEach (<anonymous>)
at PhetioStateEngine.getState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/phet-io/js/PhetioStateEngine.js:161:38)
at PhetioStateEngine.initialize (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/phet-io/js/PhetioStateEngine.js:439:30)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/phet-io/js/phetioEngine.js:241:32
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/axon/js/TinyEmitter.js:69:9)

Uncaught Error: Uncaught Error: Assertion failed: fell back to root serialization state for centerAndSpread.medianScreen.model.soccerBallGroup.soccerBall_0.animationModeProperty. Potential solutions:
* mark the type as phetioState: false
* create a custom toStateObject method in your IO Type
* perhaps you have everything right, but forgot to pass in the IOType via phetioType in the constructorError: Assertion failed: fell back to root serialization state for centerAndSpread.medianScreen.model.soccerBallGroup.soccerBall_0.animationModeProperty. Potential solutions:
* mark the type as phetioState: false
* create a custom toStateObject method in your IO Type
* perhaps you have everything right, but forgot to pass in the IOType via phetioType in the constructor
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/assert/js/assert.js:25:13)
at Object.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/tandem/js/types/IOType.js:444:15)
at IOType.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/tandem/js/types/IOType.js:182:32)
at PhetioStateEngine.getValueJSON (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/phet-io/js/PhetioStateEngine.js:107:49)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/phet-io/js/PhetioStateEngine.js:165:32
at Array.forEach (<anonymous>)
at PhetioStateEngine.getState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/phet-io/js/PhetioStateEngine.js:161:38)
at PhetioStateEngine.initialize (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/phet-io/js/PhetioStateEngine.js:439:30)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/phet-io/js/phetioEngine.js:241:32
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
id: Bayes Chrome
Snapshot from 3/3/2022, 4:24:54 AM
```

**Comment by samreid** [comment]
Thanks, @chrisklus and I fixed a PhET-iO type and this seems fixed in the latest column.  Closing.
